[general]
camara=
multimonitor=S

[timing]
ms_clic_derecho=200
ms_clic_izquierdo=200
ms_clic_central=200
ms_doble_clic_derecho=300
ms_pulsacion_derecho=800
ms_pulsacion_izquierdo=800
[DEFAULT]
# Cámara por defecto (número). Si no existe se pedirá al usuario.
camara = 

# Milisegundos para clasificar la acción al abrir el ojo
ms_clic_derecho = 200
ms_clic_izquierdo = 200
ms_clic_central = 200
ms_doble_clic_derecho = 400
ms_pulsacion_derecho = 600
ms_pulsacion_izquierdo = 600

# multimonitor: S (sí) o N (no)
multimonitor = N
